name: benchhmark
on: [push]
jobs:
  bench:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: dir
      - run: echo '::add-path::{C:\Program Files\Git\bin}'
      - run: sh.exe ./bin/benchmark run

