name: BRL-CAD

on: [push]

jobs:
  benchmark:

    name: "Windows Latest MSVC"
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - runs: dir
    - runs: ./bin/benchmark run

