name: benchhmark
on: [push]
jobs:
  bench:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: dir
      - run: "C:\Program Files\Git\bin\sh.exe" ./bin/benchmark run

